### ISSUE TITLE
REST API POST calls should nut use arrays as parameters

### ISSUE THREAD

**Issue by jpechane** [px3/SilverWare#24]
The input message should be JSON object - the name of attributes should be derived form parameter names by default and could be customized using parameter annotations

**Comment by mswiech** [comment]
from our IRC communications (with jpechane):

"The name of attributes should be derived form parameter names" - they are named as arg0, arg1... by default. So raise a warning at Silverware start to use compilation parameters:
&lt;compilerArgument&gt;-parameters&lt;/compilerArgument&gt;
&lt;testCompilerArgument&gt;-parameters&lt;/testCompilerArgument&gt;

**Comment by mswiech** [comment]
I am taking this issue.
